export const wordPairs = [
  {
    civilian: 'Pizza',
    imposter: 'Pasta',
    difficulty: 'Easy',
    bestFor: 'Family rounds and first-time players',
    tip: 'Both are familiar foods, but clues about slices, crust, or toppings can expose the imposter.',
  },
  {
    civilian: 'Lion',
    imposter: 'Tiger',
    difficulty: 'Easy',
    bestFor: 'Kids, classrooms, and warm-up rounds',
    tip: 'Strong animal clues work, but color, mane, and habitat clues create better debate.',
  },
  {
    civilian: 'Coffee',
    imposter: 'Tea',
    difficulty: 'Easy',
    bestFor: 'Casual adult groups',
    tip: 'Morning and caffeine clues are safe. Brewing details make the distinction sharper.',
  },
  {
    civilian: 'Teacher',
    imposter: 'Professor',
    difficulty: 'Medium',
    bestFor: 'School or campus theme packs',
    tip: 'The overlap is high, so players need clues about classroom level, exams, or lectures.',
  },
  {
    civilian: 'Laptop',
    imposter: 'Tablet',
    difficulty: 'Medium',
    bestFor: 'Office, tech, and team-building rounds',
    tip: 'Keyboard, work, and portability clues can point in different directions.',
  },
  {
    civilian: 'Hotel',
    imposter: 'Hostel',
    difficulty: 'Medium',
    bestFor: 'Travel groups',
    tip: 'Use clues about privacy, booking, beds, and budget without making the answer obvious.',
  },
  {
    civilian: 'Sequel',
    imposter: 'Prequel',
    difficulty: 'Medium',
    bestFor: 'Movie fans',
    tip: 'Timeline clues help civilians, but vague franchise clues can hide the imposter.',
  },
  {
    civilian: 'Deadline',
    imposter: 'Due Date',
    difficulty: 'Hard',
    bestFor: 'Experienced office groups',
    tip: 'The meanings are very close, so tone and context matter more than category.',
  },
  {
    civilian: 'Nocturnal',
    imposter: 'Diurnal',
    difficulty: 'Hard',
    bestFor: 'Players who enjoy precise clues',
    tip: 'One careless day or night clue can reveal the side immediately.',
  },
  {
    civilian: 'Plot Twist',
    imposter: 'Surprise',
    difficulty: 'Hard',
    bestFor: 'Advanced abstract rounds',
    tip: 'Civilians should hint at story structure without saying anything too cinematic.',
  },
] as const;

export const topicPacks = [
  {
    topic: 'Food & Drink',
    difficulty: 'Easy',
    bestGroup: 'Families, mixed ages, and first-time players',
    samplePairs: 'Pizza / Pasta, Coffee / Tea, Taco / Burrito',
    whyItWorks: 'Everyone knows the category, so players can focus on clue quality and bluffing.',
  },
  {
    topic: 'Animals',
    difficulty: 'Easy',
    bestGroup: 'Kids, classrooms, and fast warm-up rounds',
    samplePairs: 'Lion / Tiger, Dolphin / Whale, Bee / Wasp',
    whyItWorks: 'Concrete traits like habitat, size, sound, and appearance create clear clues.',
  },
  {
    topic: 'School Life',
    difficulty: 'Medium',
    bestGroup: 'Students, families, and classroom parties',
    samplePairs: 'Teacher / Professor, Exam / Quiz, Library / Bookstore',
    whyItWorks: 'The words are familiar but close enough to create natural suspicion.',
  },
  {
    topic: 'Office & Career',
    difficulty: 'Medium',
    bestGroup: 'Coworkers, team-building, and adult groups',
    samplePairs: 'Laptop / Tablet, Deadline / Due Date, Meeting Room / Lounge',
    whyItWorks: 'Workplace terms make good ice breakers because players share context.',
  },
  {
    topic: 'Movies',
    difficulty: 'Medium to Hard',
    bestGroup: 'Film fans and groups that like pop culture',
    samplePairs: 'Sequel / Prequel, Villain / Monster, Script / Novel',
    whyItWorks: 'Movie clues can be broad or highly specific, so discussion becomes lively.',
  },
  {
    topic: 'Travel',
    difficulty: 'Medium',
    bestGroup: 'Vacation groups, hostels, and remote friends',
    samplePairs: 'Hotel / Hostel, Suitcase / Backpack, Passport / Visa',
    whyItWorks: 'Travel words are easy to picture and work well for groups with shared trips.',
  },
] as const;
